repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
  - repo: local
    hooks:
    - id: generate-docs
      name: Generate CLI docs
      language: unsupported_script
      entry: ./scripts/generate-docs.sh
      files: src/
